DCurrent/openbor

engine/version.sh

OpenBOR was converted from Subversion to Git sometime ago. As Git didn't introduce new commits figuring out svn revision is as simple as summing up the number of git commits.
```
$ svn log -r4432 https://svn.code.sf.net/p/openbor/engine/engine/
------------------------------------------------------------------------
r4432 | whitedragon0000 | 2017-01-25 23:40:08 +0000 (Wed, 25 Jan 2017) | 1 line
added shadowopacity {-2 or -1 or 0~255} to level next prop
```
```
$ git rev-list --count ba1eb4f62cec
4432
$ git log -1 ba1eb4f62cec
commit ba1eb4f62cec7b4526bf2821e2681ad1c37df145
Author: whitedragon0000 <whitedragon0000@47506847-fb4f-4ee6-b66f-4fd32c0f12a1>
Date:   Wed Jan 25 23:40:08 2017 +0000
added shadowopacity {-2 or -1 or 0~255} to level next prop
```

Track build number in absence of Subversion metadata

---

engine/Makefile
engine/openbor.c
engine/openbor.h
engine/openborscript.c
engine/source/openborscript/entity.c
engine/source/openborscript/entity.h

This pull represents the first phase in an undertaking to rebuild scripting access from the ground up, starting with entity properties. Along the way, I am reorganizing properties, applying a big endian nomenclature where possible, optimizing the underlying logic, and documenting in the wiki.
Phase 1 changes:
- `get_entity_property(<void entity>, <char property>)` and `set_entity_property(<void entity>, <char property name>, <mixed value>'. Both reside in a dedicated file, with new enumerators and mapstring. Properties are organized in a big endian nomenclature and ordered alphabetically. The idea is to avoid haphazardly splattering properties all over the place, and keep related properties together. ONLY primary properties will be added to this list. Sub properties, model properties, …

Property Access Rework, Phase 1

---

engine/openbor.c
engine/openbor.h
engine/openborscript.c

Item structure created for entity is now used in spawn entry structure as well. Besides readability and code base reuse, it also means script authors can use the future item property functions on either just by getting the pointer.

Property access rework

---

engine/openbor.c
engine/source/gamelib/spriteq.h

Fixed the text overlap in performance option in Debug Mode.
I've defined two new constants at spriteq.h
LAYER_Z_LIMIT_MAX (INT)
LAYER_Z_LIMIT_BOX_MAX (HEX)
Co-Authored-By: msmalik681 <31506138+msmalik681@users.noreply.github.com>

Debug performance fix

---

engine/source/scriptlib/ScriptVariant.c

Bug that caused Wii port not to process "velocity" correctly bug fix from White Dragon.

Wii velocity bug fix

---

engine/wii/wiiport.c

Wii: wait for libfat to mount all devices before continuing

---

engine/sdl/control.c

In SDL 2, each joystick has a "device index" and an "instance ID", and at least on Windows, they can be different numbers. We were trying to use them interchangeably, and the result was that the control config menu would disagree with the rest of the engine about which controller was which.
Fixes https://github.com/DCurrent/openbor/issues/70

Fix input mappings being assigned to the wrong controller

---

engine/Makefile
engine/openbor.c
engine/sdl/opengl.c
engine/sdl/video.c
engine/source/savedata.h

Add support for vsync to synchronize the framerate to the monitor's refresh rate instead of using the SDL_gfx framerate manager to limit the framerate to 200 FPS. This saves energy and also lets us remove our dependency on SDL_gfx.

Support vsync

---

engine/source/gamelib/bitmap.c

It was looking at the wrong pixels, causing some non-empty sprites to be detected as empty.

Fix clipping the right side of bitmaps

---

engine/openbor.c

Legacy blast only applies blast state if entity has drop state as well (will be knocked down). Fixes #124.

Don't apply blast effect unless drop also takes effect.

---

engine/android/AndroidManifest.xml
engine/android/project.properties
engine/android/zipaglin.bat
engine/openbor.c
engine/source/gamelib/soundmix.c

disable some keys to stop logo.fig being skipped after selecting a pak from the menu and stop mutiple skips when using a text entity.
Wii port fix for the 16-bit samples playing static noise full credit to @whitedragon0000  for this fix.
Android added zipalign batch file to align a app before signing. Target API put up to 28 so apps can be uploaded to google play store.
Replace this text with a description of the changes and purpose. If the pull request resolves an issue, please cite the issue Example: Fixes #<issue number>.

small bug fixes

---

engine/source/openborscript/constants.c
engine/source/openborscript/scriptcommon.h

Other animation constants are stored in variables with `anim` prefix. Fixes #138, see [build log](https://github.com/DCurrent/openbor/files/3139804/openbor-6997.log).
CC @Plombo

Switch to e_animations for ICMPSCONSTA

---

engine/android/README
engine/android/app/build.gradle
engine/android/app/src/main/res/values/strings.xml
engine/android/build.bat
engine/android/make.my.key.bat
engine/android/sdk-setup.bat

Modified build so "app/build.gradle" file just needs to be modified to make a custom APK.  Added instruction in the README file to build on windows 10 and how to make a custom APK.  Added option to make your keystore file to sign your play store apps.

Simplified Android Build Process

---

engine/android/app/build.gradle

Quick fix for Android build not to have gradle looking at `keystore.properties` file and failed if users try to build for debug build, only release build it will try to look for such file.
In short, this PR fixes the mistake in which gradle is still trying to look for `keystore.properties` file even in Debug build.

Quick improve Android build related to keystore.properties

---

engine/Makefile
engine/source/globals.h
engine/wii/menu.c
engine/wii/wiiport.c

Various updates from Wiimpathy.
- Add devkitPPC r29+ compatibility.
-Add loader's arguments support. Load games with WiiFlow etc.
-Fix Wii Classic Controller dpad in menu.
-Fix a crash when loaded from USB without SD and with a device in port 1.

Wiimpathy Updates

---

engine/openbor.c
engine/source/ramlib/ram.c
engine/version.sh

* Improved showing commit hash in opening opebor's menu, and inside the log file (such commit hash reduced to 7 chars in length which is enough and can be directly put into browser to directly access such commit on github.com)
* Improved showing ram status with right-aligned along with human-readable unit
Example see below
**Commit hash shown in menu UI**
**Inside log file**
* Should we remove code for other version control applications inside `version.sh`? As now OpenBOR focuses and is only hosted on github. Showing commit hash is only available for git.

Improve Logging

---

engine/source/gamelib/loadimg.c

Fix decoding of interlaced PNGs with width or height not divisible by 8, cropped decoding of interlaced PNGs, and decoding of interlaced PNGs less than 8 pixels wide. This fixes compatibility with interlaced images accepted by the old decoder.

Fixes for interlaced PNG decoding

---

engine/Makefile
engine/build.sh
engine/environ.sh

This will make it easier to do cross-compile for Windows build on Linux.
In short, users just need to compile all dependencies as usual, then supply their `include` and `lib` directory via 2 newly added variables when execute `./build.sh` as follows
```
EXTRA_INCLUDES="/my/deps/sdl2-win32/include/SDL2 /my/deps/zlib-win32/include" EXTRA_LIBRARIES="/my/deps/sdl2-win32/lib /my/deps/zlib-win32/lib" ./build.sh 5
```

Improve Cross-compile support for Windows build on Linux

---

engine/source/gamelib/transform.c
engine/source/gamelib/writepixel.h

Alpha masked sprites can now be scaled and rotated without ignoring the mask. Water effects should also work in theory, but I haven't tested them.

Support combining alpha masks and drawmethod effects

---

engine/android/app/src/main/java/org/openbor/engine/GameActivity.java
engine/android/build.bat

Fixed issue with large PAK file not being copied they now need to be saved as "app\src\main\assets\bor.pak".  Changed build.bat to now generate version.h when cmopiling android build as this missing file would cause a crash.

Android Update

---

engine/source/gamelib/borendian.h

`rlwimi` ["store the rotated data in GPR RA under control of a 32-bit generated mask"](https://www.ibm.com/support/knowledgecenter/ssw_aix_71/assembler/idalangref_rlwimi_rlimi_rotwrd_instrs.html)
Reported [downstream](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=243865). CC @pkubaj

Unbreak Clang build on PowerPC

---

engine/android/app/build.gradle

Added support for minimum API down to 14 (Ice Cream Sandwich 4.0.1) as this is the minimum supported by the NDK.

API 14 - Ice Cream Sandwich 4.0.1 support

---

engine/sdl/sdlport.c

This patch allows you to use `<command>/usr/bin/openbor.start %ROM%</command>`  to load pak files in ES. 
Source:
https://retropie.org.uk/forum/post/115441

engine/sdl: add command line argument to load paks directly form cli

---

engine/Makefile

Adds two platforms for Linux LE_x86_64 & LE_arm which allows to build openbor with recent LibreELEC toolchains:
https://github.com/SupervisedThinking/LibreELEC-RR/blob/master-rr/packages/supervisedthinking/emulation/standalone/openbor/package.mk

Makefile: added Linux platforms for x86_64 & arm

---

engine/android/.gitignore
engine/android/build.sh
engine/source/globals.h
engine/version.sh

Fixed crash when reaching the bottom of the menu when there are more then 18 paks in the paks folder. Added a prompt to manually enter build number if not detected. Added android build script for Linux users.

Fixed menu crash

---

engine/openbor.c
engine/source/gamelib/translation.c

November-2021 updates
This pull request contains small fixes for the translation feature.
- Inverted the translation path priority, now the external file will override the internal file.
This is useful to maintain the english translation intact inside the pak file if no other language file is found in the external path. Otherwise you will need to put a new copy of the english file in the external path every time another language is used and then removed.
This operation is needed only if the english translation file uses some custom menu texts for english language too.
- Removed spaces on the " Done!" text to fix translation

November-2021 updates

---

engine/openbor.h
engine/openborscript.c
engine/source/openborscript/commands.c
engine/source/openborscript/commands.h

December-2021 updates
These two changes fix a bug that randomly causes the engine to crash while trying to get/change an entity property. In addition, there's some minor changes related to code organization, with no changes in the functionality
- Fixed property string names: "animation.handle" to "animation_handle", match with "_ep_animation_handle"
- Fixed property string names: "offscreennoatkfactor" to" offscreen_noatk_factor", match with "_ep_offscreen_noatk_factor"

December-2021 fixes

---

engine/openbor.c
engine/openbor.h

Minor fix on vault animation
- Fixed the "3-vault" loop bug, now will execute only once as intended
- Removed unnecessary vault constants because now the GRAB_ACTION_SELECT_FINISH works better

July-2022 fixes

---

engine/android/build.gradle
engine/android/gradle/wrapper/gradle-wrapper.properties

Fixes Android build error on gradle: `cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected`

Fix Android build error

---

engine/build.sh

I'm working on packaging OpenBOR to [flatpak](flatpak.org/) - of course if you agree (the planned name is `com.ChronoCrash.OpenBOR`).
However, I came across minor issues related to the build script:
- The script is always returning a exit code of 1 due a condition, see the first commit for more details.
Here are examples to better understand how the UNIX shell work:
```
true || printf b && printf c && printf d  #=> cd
false || printf b && printf c && printf d #=> bcd
```
- The shebang was not taken into account because it must be at the first line. This means on Debian, `dash` - the default shell - will run the script, which won't work.
-  Minor change, use the recommended parentheses notation for command substitution (`$()`), which is supported now since at least 20 years by alll systems …

Build script fixes

---

engine/source/webmlib/samplecvt.c

Since vorbis_fpu_set/get are inline functions and are not implemented for most Modern distributions, I prefer to silence the warning versus chopping up the code where these functions are referenced since unused functions and variables are eventually stripped away by linker.

Silence unused variable warning for vorbis_fpu within webm library.

---

engine/openbor.c

The following variables where initialized or updated but never referenced for actual processing thus not used.

Removed unused variables from codebase.

---

engine/openborscript.c

Compiler reported unused variable, however I believe the intent was to populate the entities projectile parameter.
Fixed water_mode assignment, previous assignment was from e_blend_mode which is invalid and can produce an unknown result between enum types for water_mode and blend_mode.

Invalid projectile reference and enum assignment

---

engine/openbor.h
engine/source/savedata.h

Pack as a whole should not be applied to all structures as they will cause cpu performance impacts due to non-native alignment.  Instead only structures that are saved to disk or read from disk should have packing applied in order to guarantee the size of the structure being written is consistent across platforms. 
This will break current saved configurations though... but moving forward they should all be consistently packed across all targets and saves can be shared across different platforms as long as endianness matches and CPU bits.

Only structures written to disk require packing.

---

engine/source/preprocessorlib/pp_parser.c

Removes unused variable that is set and incremented but never referenced.

Removed unused variable from pp_parser.c

---

engine/source/utils.c

Seems Windows port never reported the used ram size and the preprocess derivatives did not allow for MacOS support.  Reordered preprocessor derivatives and restored windows support.  Now we support all major OS platforms

Fixed preprocess checks for LINUX/DARWIN/WINDOWS

---

engine/Makefile
engine/openbor.c
engine/openbor.h
engine/sdl/opengl.c
engine/sdl/video.c
engine/sdl/video.h
engine/source/savedata.h

Reduces input latency when vsynced by not reading inputs until 4 ms before frame submission.
Also drops the dependency on SDL_gfx, replaces the SDL_gfx framerate limiter with a newly implemented simple limiter, and merges the "VSync" and "FPS limit" video options together. The possible settings for the newly combined "FPS limit" option are VSync (default), 200, 500, and disabled.

Delay before update() to reduce input latency when vsync is enabled

---

engine/sdl/opengl.c
engine/sdl/video.c

This produces better results than the windowing system's scaling on top of our own, since we can do high-quality scaling in the OpenGL backend.
Works with Windows and Wayland, and should work for Mac as well.

Support windowing system DPI scaling in OpenGL video backend

---

.gitattributes

This file will enforce proper End-Of-File handling for text files.  Which will resolve the issues encountered when setting up a new docker development environment on Windows.

.gitattributes added for proper text file handling.

---

engine/source/pnglib/savepng.c
engine/source/preprocessorlib/pp_parser.c
engine/source/ramlib/ram.c
engine/source/utils.c

Fixes building on macOS. malloc.h isn't present and wants stdlib.h instead.

Move malloc.h behind ifndef DARWIN

---

engine/openbor.c
engine/openborscript.c
engine/source/gamelib/draw.c
engine/source/gamelib/draw16.c
engine/source/gamelib/draw32.c

While reading the source i found some snippets that looked like they may be one off when checking x/y coordinates.

Add some potential out-of-bounds access prevention and wrong pixel wrapping
