- engine/openbor.c
- engine/openbor.h
- engine/openborscript.c
- engine/source/openborscript/animation.c
- engine/source/openborscript/constant.c
- engine/source/openborscript/entity.c
- engine/source/openborscript/entity.h
More memory optimizing. Jumpframe and landframe strcuts are now dynamically allocated, removing their memory footprints from animations that don't use them.
Enumerated attacking property.
More property access progress and wiki documentation.
> Property access rework

- engine/openbor.c
Fixed empty space issue (the editor on the mac had changed the empty spaces to a weird character), sorry.
> Empty space fixed

- engine/Makefile
- engine/openbor.c
- engine/wii/control.c
- engine/wii/menu.c
- engine/wii/video.c
- engine/wii/wiiport.c
- adde usb loading and can now load from any directory name.
- fixed screen scaling to fit the screen on all video modes and aspect ratios.
- added support for Wii U Pro controller (Thanks to Demothens).
> Updated wii port

- engine/openbor.c
- engine/psp/menu.c
- engine/sdl/menu.c
- engine/vita/menu.c
- engine/wii/menu.c
- Fixed PC and Android pak selection menu crash.
- Fixed default aspect ratio for all ports besides Wii.
- Removed excess files from DevkitPro.7z
> Pak Selection Fix

- engine/source/scriptlib/ScriptVariant.c
- engine/wii/menu.c
Updated the Wii port to support previews made by taking a screen shot in game.
> Malik wii update

- engine/openbor.c
Further improvements to blocking logic. Preparing for transition animations.
> Blocking fix

- engine/openbor.c
- engine/openbor.h
This update cleans up the select logic to some extent, paving the way for script access. Also adds two new animations:
- ANI_SELECTIN: Plays in select screen when new model is selected, immediately before ANI_SELECT.
- ANI_SELECTOUT: Plays in select screen when new model is selected, immediately before switching to new model.
> Select cleanup

- engine/openbor.c
Makes several improvements to debug options and code.
- Replace integer toggles for each debug option with a single bit mask.
- "Position" and "Features" option rolled into new option "Basic Properties" that provides Name, Base, XYZ position, HP, and MP values.
- Centering improved and Font 1 used differentiate labels vs. values (previously all text displayed with Font 0).
> Debug Fixes and Updates

- engine/openbor.c
- engine/source/gamelib/bitmap.c
- engine/source/gamelib/loadimg.c
- engine/source/gamelib/sprite.c
- engine/source/gamelib/types.h
Two minor improvements to the process of loading sprites. They don't make a huge impact on loading times, since loading is mostly bound to I/O speed, but they are still improvements.
> Sprite loading improvements

- engine/openbor.c
- engine/sdl/menu.c
- engine/source/gamelib/loadimg.c
- engine/source/gamelib/soundmix.c
- engine/source/gamelib/soundmix.h
- engine/source/savedata.h
- engine/wii/video.c
Several fixes, cleanups, and improvements to various things.
> Various fixes and cleanups

- engine/source/gamelib/loadimg.c
- engine/source/ramlib/ram.c
Two commits that make very minor fixes/improvements.
> Minor fixes

- engine/android/app/src/main/java/org/libsdl/app/SDLActivity.java
Before the permission request was running along side the CopyPak function. Now the CopyPak function will only run if permission granted or not needed.
> Cleaned up permission request

- README.md
> README.md link to forum is broken

- engine/source/gamelib/loadimg.c
The allocscreen() function in source/gamelib/screen.c truncates screen widths to multiples of 4. In issue #155, the decoder needed to decode a 961\*481 PNG to a 960\*481 screen, cropping off the rightmost column of pixels. But the new PNG decoder treated the cropped width as the original image width, and thus misjudged the position of the filter type bytes. Fix this by properly distinguishing between the original (input) and cropped (output) image sizes.
There are still problems loading an interlaced 961*481 PNG as the title screen background, but that's a pain to fix, and the original issue only concerns non-interlaced PNGs.
> Fix cropped PNG decoding.

- engine/openbor.c
Since .act is a Photoshop-specific format, it can be inconvenient for people without access to Photoshop. Supporting palette images as an alternative can hopefully make alternate level palettes more accessible.
> Allow alternate palettes for levels to be provided by images

- engine/openbor.c
Replace this text with a description of the changes and purpose. If the pull request resolves an issue, please cite the issue Example: Fixes #<issue number>.
> Missed a few magic numbers when implementing ITEM_HIDE_POSITION_Z.

- engine/android/README
- engine/android/script.bat
- engine/android/sdk-setup.bat
- engine/source/gamelib/font.h
- engine/source/gamelib/packfile.c
Just updated the process for setting up the android sdk as the android command line tools have changed their folder structure.  Small updated to the packfile.c as it was breaking the android build. Updated the font limit from 10 to 100.  Updated the android readme on how to compile the android build.
> Android updates & increased fonts

- engine/openbor.c
- engine/openbor.h
> Fix anim_list and model_cache definitions

- engine/Makefile
- engine/openbor.c
- engine/sdl/opengl.c
- engine/sdl/video.c
- engine/source/gamelib/packfile.c
- engine/source/scriptlib/depends.h
- engine/wii/menu.c
- engine/wii/wiiport.c
Fixes compilation with newer toolchains, and improves framerate/VSync management.
> July 2021 fixes

- README.md
Sweet project!!
Spotted tiny typo on README.md 👍
> fix: tiny typo

- engine/source/gamelib/packfile.c
Check for data folder without case sensitivity on Linux.
> Update packfile.c for Linux

- engine/openborscript.c
- engine/source/gamelib/packfile.c
Resolve issue with Linux crashing when loading from a data folder.
> Packfile fix for Linux

- engine/source/scriptlib/Instruction.h
- engine/source/scriptlib/Interpreter.c
- engine/source/scriptlib/Parser.c
- engine/source/scriptlib/ScriptVariant.c
- engine/source/scriptlib/ScriptVariant.h
Implement's @Plombo's solution for bitwise not operator. Fixes #257.
> Fix Bitwise not (~) operator

- engine/source/ramlib/ram.c
- engine/source/utils.c
Added mallinfo2 for Linux distros running glibc 2.33+
Would appreciate it if @Plombo could review to make sure everything is ok.
> fixing mallinfo for glibc 2.33+

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- COMPILING.md
This PR contains a few updates to the Dockerfile framework and instructions on how to build openbor using the new Cmake configuration system and Docker for cross-compilation of all supported targets.
For a brief view of the COMPILING.md visit my branch:
https://github.com/SumolX/openbor/blob/compiling/COMPILING.md
> Compilation Instructions

- .github/build_and_release.yml
- cmake/linux.cmake
- cmake/macos-finalize.cmake
- cmake/wii.cmake
- cmake/windows-finalize.cmake
- cmake/windows.cmake
- engine/sdl/video.c
Replace this text with a description of the changes and purpose. If the pull request resolves an issue, please cite the issue Example: Fixes #<issue number>.
> GitHub Actions will now build MacOS, Win32/64 and Ubuntu 64

- .github/workflows/build_and_release.yml
- engine/version.sh
GitHub action now applies version info to artifacts.
> Added version info to artifacts

- .github/workflows/build_and_release.yml
- engine/version.sh
Now reports proper build via GitHub action
> Fixed github action version history

- engine/Makefile
quick fix for anyone compiling without docker.
> legacy compile fix
